### ISSUE TITLE
Swap always shows 100%

### ISSUE THREAD

**Issue by Olian04** [aksakalli/gtop#60] opened 2017-10-31 13:12 UTC
#### Environment

- OS: Linux (Ubuntu 17.04)
- Node version: 8.8.1
- gtop version: 0.1.5

#### Description

The swap segment shows 100% when only 102.80mb out of 7.91gb is used

![image](https://user-images.githubusercontent.com/5493406/32225331-155beb66-be45-11e7-9f9e-bf92b2e63bf3.png)

**Comment by felleg** [comment] 2017-10-31 16:00
I have:
    OS: Ubuntu 16.04
    Node version: v4.2.6
    gtop version: 0.1.5
I'm not able to reproduce this issue!
![screenshot from 2017-10-31 12-00-28](https://user-images.githubusercontent.com/7781739/32234420-1ab803ae-be33-11e7-87f0-941d1f1fee0c.png)

**Comment by Olian04** [comment] 2017-10-31 16:02
You don't have the same node version nor the same Ubuntu version as me.

**Comment by xcjs** [comment] 2018-01-30 22:00
@felleg 

The used is in MiB and the total is in GiB, but gtop sees that 102.80 > 7.91 without adjusting for the difference of scale.

**Comment by Maxattax97** [comment] 2018-08-13 14:56
Same issue here.
`81.75 MiB of 15.90 GiB` yet the circle is full.

**Comment by aksakalli** [comment] 2018-09-23 13:40
should be fixed for `v0.1.6`, thank you for reporting.

**Closed by aksakalli** 2018-09-23 13:40 UTC
