### ISSUE TITLE
Rendering Errors with many cpu cores

### ISSUE THREAD

**Issue by nickwanninger** [aksakalli/gtop#77] opened 2018-07-22 19:55 UTC
#### Environment

- OS: Linux 4.15.0-29-generic #31-Ubuntu 18.04 x86_64 x86_64 x86_64 GNU/Linux
- Node version: v8.10.0
- gtop version: 0.1.5

#### Description

One of my machines has 32 cores, and they seem to overflow to the memory view.

![image](https://user-images.githubusercontent.com/8473174/43049550-a2ddd16e-8dc7-11e8-917d-d923dca40ca6.png)

**Comment by aksakalli** [comment] 2018-09-23 13:35
duplicate of #34

**Closed by aksakalli** 2018-09-23 13:35 UTC
