### ISSUE TITLE
Insane memory usage

### ISSUE THREAD

**Issue by miguelmota** [aksakalli/gtop#54] opened 2017-09-28 15:29 UTC
#### Environment

- OS: macOS
- Node version: 7.9
- gtop version: 0.1.5

#### Description

gtop takes up a ton of memory; uses more memory than some processes I'm trying to monitor.

for comparison

![htop_vs_gtop](https://user-images.githubusercontent.com/168240/30975400-0a07b034-a427-11e7-930b-4d4747e7d47b.png)

**Comment by ritiek** [comment] 2017-09-28 15:45
Duplicate of #12.

**Closed** 2017-10-06 08:26 UTC
